<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyApi.Business.Contracts\MyApi.Business.Contracts.csproj" />
    <ProjectReference Include="..\MyApi.Entity\MyApi.Entity.csproj" />
    <ProjectReference Include="..\MyApi.Repository.Contracts\MyApi.Repository.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
