<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyApiTest.Repository.Contracts\MyApiTest.Repository.Contracts.csproj" />
    <ProjectReference Include="..\MyApiTest.Entity\MyApiTest.Entity.csproj" />
    <ProjectReference Include="..\MyApiTest.EntitiesContext\MyApiTest.EntitiesContext.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
